/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        PushButton startButton = new PushButton();
        PushButton stopButton = new PushButton();
        PilotLamp startLamp = new PilotLamp();

        startButton.setTerminal("X0");
        startButton.setName("起動ボタン");
        stopButton.setTerminal("X1");
        stopButton.setName("停止ボタン");
        startLamp.setTerminal("Y0");
        startLamp.setName("起動ランプ");

        if (!startButton.press()) {
            System.out.println("起動に失敗しました。");
            System.exit(1);
        }

        System.out.println(startLamp.getStatusString());

        if (!stopButton.press()) {
            System.out.println("停止に失敗しました。");
            System.exit(1);
        }

        System.out.println(startLamp.getStatusString());

        /*
        PilotLampStatus startLampStatus= startLamp.getStatus(); 
        if (startLampStatus == PilotLampStatus.ERROR) {
            System.out.println("起動ランプの状態取得に失敗しました。");
            System.exit(1);
        } else if (startLampStatus == PilotLampStaus.ON) {
            System.out.println("起動ランプは点灯しています。");
        } else if (startLampStatus == PilotLampStaus.OFF) {
            System.out.println("起動ランプは消灯しています。");
        }

        if (!stopButton.press()) {
            System.out.println("停止に失敗しました。");
            System.exit(1);
        }

        PilotLampStatus startLampStatus= startLamp.getStatus(); 
        if (startLampStatus == PilotLampStatus.ERROR) {
            System.out.println("起動ランプの状態取得に失敗しました。");
            System.exit(1);
        } else if (startLampStatus == PilotLampStaus.ON) {
            System.out.println("起動ランプは点灯しています。");
        } else if (startLampStatus == PilotLampStaus.OFF) {
            System.out.println("起動ランプは消灯しています。");
        }
        */
    }
}
