/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        PushButton startButton = new PushButton();
        PushButton stopButton = new PushButton();
        PilotLamp startLamp = new PilotLamp();

        startButton.setTerminal("X0");
        startButton.setName("起動ボタン");
        startButton.setRole(ButtonRole.ON);
        startButton.setTarget(startLamp);

        stopButton.setTerminal("X1");
        stopButton.setName("停止ボタン");
        stopButton.setRole(ButtonRole.OFF);
        stopButton.setTarget(startLamp);
        
        startLamp.setTerminal("Y0");
        startLamp.setName("起動ランプ");

        if (!startButton.press()) {
            System.out.println("起動に失敗しました。");
            System.exit(1);
        }

        System.out.println(startLamp.getStatusString());

        if (!stopButton.press()) {
            System.out.println("停止に失敗しました。");
            System.exit(1);
        }

        System.out.println(startLamp.getStatusString());
    }
}
