/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import java.sql.*;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) 
        throws ClassNotFoundException, SQLException {

        System.out.println(new App().getGreeting());

        Class.forName("org.h2.Driver");
        Connection con = DriverManager.getConnection("jdbc:h2:~/test","","");
    }
}
